### ISSUE TITLE
Stock Ticker is Case Sensitive Issue

### ISSUE THREAD

**Issue by JonesZack** [fekberg/getting-started-with-asynchronous-programming-dotnet#15]
Filip,

The page on Pluralsight isn't loading properly tonight so I figured I'd reach out to you here. I was getting a 404 error on line 33 of the MainWindow.xaml.cs file because instead of entering "MSFT" for the ticker I was entering "msft" It seems the API is case sensitive. I fixed the problem by changing {Ticker.Text} to {Ticker.Text.ToUpper()}. I tried to do a fork so I could change the source myself but that didn't go so well :).

**Comment by fekberg** [comment]
Thanks for reaching out @JonesZack! 

It is, and that is a great suggestion for a fix to improve the application. Ideally when comparing strings where you don't care about upper/lower, you can do `ToLowerInvariant()` which will allow you to lower case without caring about the current culture.
