### ISSUE TITLE
NuGet Package restore failed

### ISSUE THREAD

**Issue by tom1944** [fekberg/getting-started-with-asynchronous-programming-dotnet#17]
I am following your PluralSight course about asynchronous programming in .NET. When opening any of the projects in a `Start_Here` directory, I get the following message in the Error List:

`
NuGet Package restore failed for project StockAnalyzer.Web: Could not find a part of the path 'C:\pluralsight\getting-started-with-asynchronous-programming-dotnet\src\Windows\02\Start_Here\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.0\build/net45/Microsoft.CodeDom.Providers.DotNetCompilerPlatform.Extensions.props'.. Please see Error List window for detailed warnings and errors.
`

I am using Visual Studio 2019 on Windows. Have searched the web for a while, but no resolution so far. Any ideas?

**Comment by fekberg** [comment]
Hi @tom1944,

Did you try Restore Nuget Packages, Clean and Rebuild?

**Comment by tom1944** [comment]
Hi Filip,

Thanks for your reply. I tried Restore Nuget Packages, Clean and Rebuild, but it didn't fix it. When trying to build the project, it says it cannot find any component, including `System.*`.

Edit: the issue can possibly be caused by some policy that my company is using. I am quite new in the world of software development, will let you know when I have a resolution.

**Comment by fekberg** [comment]
@tom1944 Thanks for clarifying!

Can you try a few things to see if that helps:
1. Extract the code in C:\Code to minimize the file path
2. Run Visual Studio as Administrator
3. Remove the obj/bin folders and restart Visual Studio

It really should work..

**Comment by tom1944** [comment]
The long file path appeared to be the problem. Thanks for helping out!
